steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/nani-food-dev/simple-api-clound-run', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/nani-food-dev/simple-api-clound-run']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'simple-api-clound-run', '--image', 'gcr.io/nani-food-dev/simple-api-clound-run', '--region', 'REGION', '--platform', 'managed', '--port', '3000']
images:
- gcr.io/nani-food-dev/simple-api-clound-run