steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/simple-api-cloudrun-mysql:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/simple-api-cloudrun-mysql:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy',
    'simple-api-cloudrun-mysql',
    '--image',
    'gcr.io/${PROJECT_ID}/simple-api-cloudrun-mysql:$COMMIT_SHA',
    '--region',
    'us-central1',
    '--allow-unauthenticated',
    '--add-cloudsql-instances',
    'nani-food-dev:us-central1:db-nani-food-dev',
    '--set-env-vars',
    'INSTANCE_UNIX_SOCKET=/cloudsql/${PROJECT_ID}:us-central1:db-nani-food-dev',
    '--set-env-vars',
    'INSTANCE_CONNECTION_NAME=${PROJECT_ID}:us-central1:db-nani-food-dev',
    '--set-env-vars',
    'DB_NAME=db-nani-food-dev',
    '--set-env-vars',
    'DB_USER=nani-user-db',
    '--set-env-vars',
    'DB_PASS=1aq2sw3de',
    '--set-env-vars',
    'CLOUD_SQL_CREDENTIALS_SECRET=projects/500573227005/secrets/CLOUD_SQL_CREDENTIALS_SECRET/1'
  ]
images:
- gcr.io/${PROJECT_ID}/simple-api-cloudrun-mysql:$COMMIT_SHA

